# https://bettercodehub.com

# Search for project directories in the root dir (level 1).
component_depth: 1

languages:
  - name: python

    production:
      include:
        # The CLI app lacks extension.
        - /bin/pstore
      exclude:
        - /contrib/.*
        - /setups.py

    test:
      include:
        - /pstore/tests/.*
