# Generated by Django 4.1.10 on 2024-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
