# Generated by Django 4.1.10 on 2024-02-27 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pstore', '0003_publickey_add_keyid_expiresat'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='can_decrypt',
            field=models.BooleanField(blank=True, default=True, help_text='A user should have at least one can_decrypt key. Keys without are only useful to authenticate for writing. This can be useful in some places where new passwords are set but not read.'),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publickey', to=settings.AUTH_USER_MODEL),
        ),
    ]
